;(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
;                         ("marmalade" . "http://marmalade-repo.org/packages/")
;                         ("melpa" . "http://melpa.milkbox.net/packages/")))
(require 'package)
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
(setq package-enable-at-startup nil)
(package-initialize)
(unless package-archive-contents (package-refresh-contents))
(package-install 'smex)
;;(package-install 'icicles)
(package-install 'recentf-ext)
(package-install 'multiple-cursors)
(recentf-mode t)
(ido-mode t)
(set-face-attribute 'default nil :font "consolas-11:weight=normal")
(defun my-delete-region (&optional arg)
  (interactive "p")
  (setq is-line-end (= (line-end-position) (point-max)))
  (setq start (if is-line-end (- (line-beginning-position) 1) (line-beginning-position)))
  (setq end (if is-line-end (line-end-position) (+ 1 (line-end-position))))
  (delete-region start end)
  )
(global-set-key (kbd "C-k") 'my-delete-region)
(global-set-key (kbd "M-x") 'smex)
